# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dallin Coons
email: dallinis@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dallin Coon's learning documented
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dallincoons.github.io" # the base hostname & protocol for your site
twitter_username: DallinCoons
github_username:  dallincoons

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
